language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
env:
 - DJANGO=Django==1.4.8
 - DJANGO=Django==1.5.4
 - DJANGO="git+git://github.com/django/django.git@master#egg=django"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
 - pip install $DJANGO --use-mirrors
 - pip install . --use-mirrors
 - pip install coverage
branches:
 only:
  - master
script: coverage run manage.py test account socialaccount dropbox facebook google github linkedin openid persona soundcloud stackexchange twitch twitter vimeo vk weibo bitly
matrix:
  allow_failures:
    - env: DJANGO="git+git://github.com/django/django.git@master#egg=django"
  exclude:
    - python: "2.6"
      env: DJANGO="git+git://github.com/django/django.git@master#egg=django"
    - python: "3.3"
      env: DJANGO=Django==1.4.8
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
 
