language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
env:
  global:
   - TEST_APPS="allauth account socialaccount amazon angellist bitbucket coinbase dropbox feedly foursquare facebook flickr google github hubic instagram linkedin linkedin_oauth2 mailru odnoklassniki windowslive openid orcid paypal persona soundcloud stackexchange tumblr twitch twitter vimeo vk weibo bitly xing"
  matrix:
   - DJANGO=Django==1.4.3
   - DJANGO=Django==1.5
   - DJANGO=Django==1.6
   - DJANGO=Django==1.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
 - pip install $DJANGO --use-mirrors
 - pip install . --use-mirrors
 - pip install coverage
branches:
 only:
  - master
script: if [ $DJANGO == Django==1.4.3 -o $DJANGO == Django==1.5 ]; then coverage run manage.py test $TEST_APPS; else coverage run manage.py test allauth; fi
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=Django==1.4.3
    - python: "3.3"
      env: DJANGO=Django==1.4.3
    - python: "3.2"
      env: DJANGO=Django==1.4.3
    - python: "2.6"
      env: DJANGO=Django==1.7
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
