# https://travis-ci.org/pennersr/django-allauth
language: python
dist: focal

matrix:
  fast_finish: true
  include:
    # Python 3.5
    - python: 3.5
      env: TOXENV=py35-django20,py35-django21,py35-django22

    # Python 3.6
    - python: 3.6
      env: TOXENV=py36-django20,py36-django21,py36-django22,py36-django30,py36-django31,py36-django32

    # Python 3.7
    - python: 3.7
      env: TOXENV=py37-django20,py37-django21,py37-django22,py37-django30,py37-django31,py37-django32,docs,checkqa,standardjs

    # Python 3.8
    - python: 3.8
      env: TOXENV=py38-django22,py38-django30,py38-django31,py38-django32

    # Python 3.9
    - python: 3.9
      env: TOXENV=py39-django22,py39-django30,py39-django31,py39-django32

    # Django Master
    - python: 3.8
      env: TOXENV=py38-djangomaster

  allow_failures:
    - python: 3.8
      env: TOXENV=py38-djangomaster

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - if [[ $TOXENV == "standardjs" ]]; then nvm install 8; fi
  - pip install --upgrade pip wheel setuptools
  - pip install coveralls tox

script:
  - tox

after_success:
  - coveralls

branches:
 only:
  - master

notifications:
  webhooks:
    urls:
      - https://readthedocs.org/build/django-allauth
    on_start: never
    on_cancel: never
    on_error: never
    on_failure: never
    on_success: always
