name: CI

on:
  push:
    branches: [ main, '0.55.x' ]
  pull_request:
    branches: [ main, '0.55.x' ]

jobs:
  testenv:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        django-version: ['main', '3.2', '4.0', '4.1', '4.2']
        exclude:
          - python-version: '3.11'
            django-version: '3.2'

          - python-version: '3.7'
            django-version: '4.0'
          - python-version: '3.11'
            django-version: '4.0'

          - python-version: '3.7'
            django-version: '4.1'

          - python-version: '3.7'
            django-version: '4.2'

          - python-version: '3.7'
            django-version: 'main'
          - python-version: '3.8'
            django-version: 'main'
          - python-version: '3.9'
            django-version: 'main'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install xmlsec
      run: sudo apt-get install -y xmlsec1 libxmlsec1-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions coveralls
    - name: Tox Test
      run: tox
      env:
        PYTHON_VER: ${{ matrix.python-version }}
        DJANGO: ${{ matrix.django-version }}
    - name: Coverage (Coveralls)
      if: ${{ success() }}
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  extra:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        extra-env: ['docs', 'black', 'isort', 'flake8', 'standardjs']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      if: ${{ matrix.extra-env == 'standardjs' }}
      with:
        node-version: '8'
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install xmlsec
      run: sudo apt-get install -y xmlsec1 libxmlsec1-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Tox Test
      run: tox
      env:
        TOXENV: ${{ matrix.extra-env }}
